### ISSUE TITLE
Temporal Network node names cant be integers if you visualize.

### ISSUE THREAD

**Issue by user1246638** [uzhdag/pathpy#29]
Error message:
pathpy\visualisation\html.py in fix_node_name(v)
    486     def fix_node_name(v):
    487         new_v = v
--> 488         if v[0].isdigit():
    489             new_v = "n_" + v
    490         if new_v[0] == '_':

TypeError: 'int' object is not subscriptable

Reproduction code:

test = pp.TemporalNetwork()
test.add_edge(1,0,1)
test

**Comment by verginer** [comment]
Hi @user1246638 thanks for the report, we appreciate all feedback! 👍 

This is a bug which has been reported in #26 and fixed on the development branch (i.e. not yet pushed to `pip`).

If you use the GitHub version of pathpy the issue should be resolved, we are working on the next release to fix this issue.

If you need nay help in setting up pathpy from Github, let me know.

**Comment by user1246638** [comment]
Hi Luca,

I am quite sure that I am right. Ingo fixed the one for the networks, but there is the same issue again with temporal networks. In html.py in visualization, function `fix_node_name` is defined twice (at least). Temporal network and regular network are treated separately.

Nice to meet you, btw, I'm one of Ingo's two students, I heard a lot about you.

Best, 
Luka

**Comment by user1246638** [comment]
> Hi Lukas, sorry you are right, I didn't mean to say you are wrong and in fact you are referring to a different class.
No problem, I see where you are coming from. 
I thought I am crazy when I pulled pathpy again, reinstalled and the bug was still occuring, even after 2 reinstallations xD.

> Although the same fix is applicable here.
> Welcome to the team :)
Thanks!

> 
> P.S.: Could you add your name to the github account, talking to user1246638 does not come natural :)
Yes, xD.

**Comment by IngoScholtes** [comment]
Hi Luka 

Indeed, I have only fixed this in the Network class. I will apply the same to TemporalNetwork. 

Best 

Ingo
